name: Needs user action.

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read
  issues: write

jobs:
  needs-user-action:
    runs-on: ubuntu-slim
    steps:
      - uses: godofredoc/no-response@v0.5.1
        with:
          token: ${{ github.token }}
          responseRequiredLabel: needs user action
