name: Waiting for answer.

on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '30 0 * * *'

permissions:
  contents: read
  issues: write

jobs:
  waiting-for-answer:
    runs-on: ubuntu-slim
    steps:
      - uses: godofredoc/no-response@v0.5.1
        with:
          token: ${{ github.token }}
          responseRequiredLabel: waiting for answer
